# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "rgl-fold"
  s.version = "0.4.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joshua B. Griffith"]
  s.date = "2012-02-10"
  s.description = "Fold for Ruby Graph Library graphs"
  s.email = "josh.griffith@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Guardfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "doc/img/graph.png",
    "lib/rgl-fold.rb",
    "rgl-fold.gemspec",
    "spec/rgl-fold_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "https://github.com/hadronzoo/rgl-fold"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Fold for RGL graphs"
  s.add_runtime_dependency(%q<forforf-rgl>, ["~> 0.5"])
    
  
end

